services:
  my_nginx:
    restart: always
    image: hvostovan/my_nginx
    build: ../my_nginx
    ports:
      - 80:80
      - 443:443 
    volumes:
      - /etc/ssl/private:/etc/nginx/ssl

  flask1:
    restart: always
    image: hvostovan/flask
    build: ../flask
    ports:
      - 8080:8080
    environment:
      SERVER_NAME: flask1

  flask2:
    restart: always
    image: hvostovan/flask
    ports:
      - 8081:8080
    environment:
      SERVER_NAME: flask2

  flask3:
    restart: always
    image: hvostovan/flask
    ports:
      - 8082:8080
    environment:
      SERVER_NAME: flask3
